-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 14:25:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autoglass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autoglass` ;

-- -----------------------------------------------------
-- Schema autoglass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoglass` DEFAULT CHARACTER SET utf8 ;
USE `autoglass` ;

-- -----------------------------------------------------
-- Table `autoglass`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`Customer` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`Customer` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `Emal` VARCHAR(60) NOT NULL,
  `First Name` VARCHAR(45) NOT NULL,
  `Last Name` VARCHAR(45) NULL,
  `Phone Number` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `Customercol` VARCHAR(45) NULL,
  `Owner` INT NOT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoglass`.`Quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`Quote` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`Quote` (
  `Quote_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NULL,
  `Submitted_Date` DATE NULL,
  `Make` VARCHAR(100) NULL,
  `Model` VARCHAR(100) NOT NULL,
  `Year` YEAR(4) NOT NULL,
  `Style` VARCHAR(45) NOT NULL,
  `Vin Number` VARCHAR(45) NULL,
  `Final Evaluation Price` INT NOT NULL,
  `Final Evaluation` BLOB NULL,
  `Quotecol` VARCHAR(45) NULL,
  PRIMARY KEY (`Quote_ID`),
  INDEX `Customer_ID_idx` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `Customer_ID`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `autoglass`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoglass`.`Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`Company` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`Company` (
  `Company_ID` INT NOT NULL AUTO_INCREMENT,
  `Owner` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  PRIMARY KEY (`Company_ID`),
  INDEX `Owner_idx` (`Owner` ASC) VISIBLE,
  CONSTRAINT `Owner`
    FOREIGN KEY (`Owner`)
    REFERENCES `autoglass`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoglass`.`Fleets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`Fleets` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`Fleets` (
  `Fleet_ID` INT NOT NULL AUTO_INCREMENT,
  `Vehicle Number` INT NOT NULL,
  `Contact Person` INT NOT NULL,
  `Company_ID` INT NOT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`Fleet_ID`),
  INDEX `company_id_idx` (`Company_ID` ASC) VISIBLE,
  CONSTRAINT `company_id`
    FOREIGN KEY (`Company_ID`)
    REFERENCES `autoglass`.`Company` (`Company_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoglass`.`Car_Damage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`Car_Damage` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`Car_Damage` (
  `Damage_ID` INT NOT NULL AUTO_INCREMENT,
  `Car_ID` INT NOT NULL,
  `Damage_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Damage_ID`),
  INDEX `Fleet_ID_idx` (`Car_ID` ASC) VISIBLE,
  CONSTRAINT `Fleet_ID`
    FOREIGN KEY (`Car_ID`)
    REFERENCES `autoglass`.`Fleets` (`Fleet_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoglass`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`Services` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`Services` (
  `Serivce_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Damage` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Serivce_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoglass`.`service_for_damage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`service_for_damage` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`service_for_damage` (
  `Services_ID` INT NOT NULL,
  `Damage_ID` VARCHAR(45) NULL,
  INDEX `fk_Services_has_Car_Damage_Services1_idx` (`Services_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Services_has_Car_Damage_Services1`
    FOREIGN KEY (`Services_ID`)
    REFERENCES `autoglass`.`Services` (`Serivce_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Damage_Type`
    FOREIGN KEY ()
    REFERENCES `autoglass`.`Car_Damage` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autoglass`.`Quote_has_Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`Quote_has_Services` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`Quote_has_Services` (
  `Quote_Quote_ID` INT NOT NULL,
  `Services_Serivce_ID` INT NOT NULL,
  PRIMARY KEY (`Quote_Quote_ID`, `Services_Serivce_ID`),
  INDEX `fk_Quote_has_Services_Services1_idx` (`Services_Serivce_ID` ASC) VISIBLE,
  INDEX `fk_Quote_has_Services_Quote1_idx` (`Quote_Quote_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Quote_has_Services_Quote1`
    FOREIGN KEY (`Quote_Quote_ID`)
    REFERENCES `autoglass`.`Quote` (`Quote_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quote_has_Services_Services1`
    FOREIGN KEY (`Services_Serivce_ID`)
    REFERENCES `autoglass`.`Services` (`Serivce_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
