-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 16:27:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema autoglass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autoglass` ;

-- -----------------------------------------------------
-- Schema autoglass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoglass` DEFAULT CHARACTER SET utf8 ;
USE `autoglass` ;

-- -----------------------------------------------------
-- Table `autoglass`.`car_damage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`car_damage` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`car_damage` (
  `Damage_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Car_ID` INT(11) NOT NULL,
  `Quote_form_ID` INT(11) NOT NULL,
  `Repair` VARCHAR(45) NULL DEFAULT NULL,
  `Chips` VARCHAR(45) NULL DEFAULT NULL,
  `Back_glass` VARCHAR(45) NULL DEFAULT NULL,
  `Side_glass` VARCHAR(45) NULL DEFAULT NULL,
  `Door_glass` VARCHAR(45) NULL DEFAULT NULL,
  `Vent_glass` VARCHAR(45) NULL DEFAULT NULL,
  `Quarter_glass` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Damage_ID`),
  INDEX `Fleet_ID_idx` (`Car_ID` ASC) VISIBLE,
  INDEX `Quote_form_ID_idx` (`Quote_form_ID` ASC) VISIBLE,
  CONSTRAINT `Fleet_ID`
    FOREIGN KEY (`Car_ID`)
    REFERENCES `autoglass`.`fleets` (`Fleet_ID`),
  CONSTRAINT `Quote_form_ID`
    FOREIGN KEY (`Quote_form_ID`)
    REFERENCES `autoglass`.`quote` (`Quote_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autoglass`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`company` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`company` (
  `Company_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Owner` INT(11) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Company_ID`),
  INDEX `Owner_idx` (`Owner` ASC) VISIBLE,
  CONSTRAINT `Owner`
    FOREIGN KEY (`Owner`)
    REFERENCES `autoglass`.`customer` (`Customer_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autoglass`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`customer` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`customer` (
  `Customer_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(60) NOT NULL,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autoglass`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`employee` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`employee` (
  `employee_id` INT(11) NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Last_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autoglass`.`fleets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`fleets` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`fleets` (
  `Fleet_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Contact_Person` INT(11) NOT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Fleet_ID`),
  INDEX `Contact_Person_idx` (`Contact_Person` ASC) VISIBLE,
  CONSTRAINT `Contact_Person`
    FOREIGN KEY (`Contact_Person`)
    REFERENCES `autoglass`.`customer` (`Customer_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autoglass`.`quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`quote` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`quote` (
  `Quote_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT(11) NULL DEFAULT NULL,
  `Submitted_Date` DATE NULL DEFAULT NULL,
  `Make` VARCHAR(100) NULL DEFAULT NULL,
  `Model` VARCHAR(100) NOT NULL,
  `Year` VARCHAR(45) NOT NULL,
  `Style` VARCHAR(45) NOT NULL,
  `Vin_Number` VARCHAR(45) NULL DEFAULT NULL,
  `Final_Evaluation_Price` INT(11) NULL DEFAULT NULL,
  `Final_Evaluation` BLOB NULL DEFAULT NULL,
  `Payment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Quote_ID`),
  INDEX `Customer_ID_idx` (`Customer_ID` ASC) VISIBLE,
  CONSTRAINT `Customer_ID`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `autoglass`.`customer` (`Customer_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autoglass`.`quote_has_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`quote_has_services` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`quote_has_services` (
  `Quote_Quote_ID` INT(11) NOT NULL,
  `Services_Serivce_ID` INT(11) NOT NULL,
  PRIMARY KEY (`Quote_Quote_ID`, `Services_Serivce_ID`),
  INDEX `fk_Quote_has_Services_Services1_idx` (`Services_Serivce_ID` ASC) VISIBLE,
  INDEX `fk_Quote_has_Services_Quote1_idx` (`Quote_Quote_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Quote_has_Services_Quote1`
    FOREIGN KEY (`Quote_Quote_ID`)
    REFERENCES `autoglass`.`quote` (`Quote_ID`),
  CONSTRAINT `fk_Quote_has_Services_Services1`
    FOREIGN KEY (`Services_Serivce_ID`)
    REFERENCES `autoglass`.`services` (`Serivce_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `autoglass`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoglass`.`services` ;

CREATE TABLE IF NOT EXISTS `autoglass`.`services` (
  `Serivce_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Damage` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Serivce_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
